### ISSUE TITLE
Latest update from Gnome extensions broke the previous fix

### ISSUE THREAD

**Issue by in4matix** [cankurttekin/PinIt-Gnome-Extension#2]
Hey, I uninstalled the extension and re-installed it again from the Gnome extensions website,  but the white theme with unreadable text issue is persistent?

![339204108-c16c85e0-6954-4c7c-854d-93941ae0a05f](https://github.com/cankurttekin/PinIt-Gnome-Extension/assets/62904593/dca7115d-1a95-4a5f-b443-df095270fb35)

Ubuntu 22.04 LTS (Gnome 42.9)

**Comment by in4matix** [comment]
The version that it updated to is v4. I tried a manual installation, now have below:

![s2](https://github.com/cankurttekin/PinIt-Gnome-Extension/assets/62904593/c2ffe844-6013-4764-9ee5-0140683cbdd4)

But my shell theme is dark?

Maybe it is the theme I'm using? Because on a Ubuntu 22 VM with Yaru Dark theme, it looks correct:

![s4](https://github.com/cankurttekin/PinIt-Gnome-Extension/assets/62904593/818664d5-9cf5-4cca-805f-41a9422c965d)

**Comment by cankurttekin** [comment]
@in4matix hey i couldnt update the extension on gnome page, i was a bit busy lately, it might not be the best to use the one on github. I will check today.
For the dark mode, it works by getting color-scheme from gnome.interface and if that value includes "dark" it changes to dark mod. So if your third party theme change your desktop interface to darker colors but keep color-scheme as light this might be the issue.
Can you paste this to your terminal and post your output here
`$ gsettings get org.gnome.desktop.interface color-scheme`   (this will display your color scheme value)

**Comment by in4matix** [comment]
Hey, no worries. It amazes me that such a small Application can do so much !! The one from the Gnome website is an old version, ver 4 and the one from Github is ver 8... Anyway, here is what I get in terminal:

```
daniel@dkdt:~$ gsettings get org.gnome.desktop.interface color-scheme
'prefer-light'
daniel@dkdt:~$
```
But my shell theme is dark and my Applications theme is light?

![Screenshot from 2024-06-26 16-14-15](https://github.com/cankurttekin/PinIt-Gnome-Extension/assets/62904593/d77360b5-47b6-4996-ac1b-7d7a8eb0da82)
![Screenshot from 2024-06-26 16-15-48](https://github.com/cankurttekin/PinIt-Gnome-Extension/assets/62904593/ea503160-2a1b-45c5-820c-7454e94ebb52)

Maybe a setting to set the theme manually?

**Comment by cankurttekin** [comment]
@in4matix 

i forgot to ask, can you also provide gtk-theme with this command:
`gsettings get org.gnome.desktop.interface gtk-theme`

> The one from the Gnome website is an old version, ver 4 and the one from Github is ver 8...

Version 5+ for Gnome 45 and 46
Version 1-4.+ for older gnomes. you probably dont see version 5+ available on gnome.extensions because your system is 42.9.

> Maybe a setting to set the theme manually?

I dont want to add theme setting to extension as i want to keep it as clean looking as possible and also dont want to make it permanently dark as i never use dark mode. Will find a better solution i might both check gtk theme and color scheme if one of them has dark in its name that should be accepted.

**Comment by in4matix** [comment]
@cankurttekin , Here is terminal output:

```
daniel@dkdt:~$ gsettings get org.gnome.desktop.interface gtk-theme
'WhiteSur-Glassy-Light-blue'
daniel@dkdt:~$
```

This is the version number in Extension Manager:

![PinIt-version](https://github.com/cankurttekin/PinIt-Gnome-Extension/assets/62904593/b0fb40d8-ccd2-407a-97dd-8b832e991827)

**Comment by cankurttekin** [comment]
So, i cant get any name from your system. If i check for light i will get light mode from 'WhiteSur-Glassy-Light-blue' but theme developer made it look dark. Solution to this will conflict on others system who use stock or properly named themes.
I added settings page for 
![image](https://github.com/cankurttekin/PinIt-Gnome-Extension/assets/29798399/bbc14d7b-0946-49f8-b54c-4d52c54feb10)
 I dont know if this will solve your problem, you will get probably white input fields from 'WhiteSur-Glassy-Light-blue' but dark dialog window if you choose 'Dark' option instead of 'Follow system'.
But also you may try editing css file as you wish if you know how to do it

**Comment by in4matix** [comment]
> I dont know if this will solve your problem, you will get probably white input fields from 'WhiteSur-Glassy-Light-blue' but dark dialog window if you choose 'Dark' option instead of 'Follow system'.

Good guess, about the white input fields being white regardless of which theme is selected. But all my other extensions that use input fields, e.g. ArcMenu, work correctly...

> But also you may try editing css file as you wish if you know how to do it

Can you maybe point to the line numbers that is responsible for handling input fields?

**Comment by cankurttekin** [comment]
@in4matix hey, a bit late again. Did latest update on EGO fix your issue? You dont have to edit any css file and you can use any theme you want now. Extension no longer creates custom window with my color choices, it displays as popup menu like any other system menu so whatever color scheme you have it should display that way in menu and input fields.

**Comment by in4matix** [comment]
Hey, yes indeed! Thanks!
Where does the extension get it's icons from? Is there maybe a way to change the icons, or to maybe hardcode icons? I would like the icons to be smaller. Should I open a separate issue for this?
![Screenshot from 2024-07-11 04-34-52](https://github.com/cankurttekin/PinIt-Gnome-Extension/assets/62904593/22bbad7f-2267-414f-8250-4ba0cb2aac82)

**Comment by cankurttekin** [comment]
yeah, please open a new issue. here became like a chatroom lol.

**Comment by in4matix** [comment]
Thanks again for fixing this.
