### ISSUE TITLE
Icons are too large and some are missing

### ISSUE THREAD

**Issue by in4matix** [cankurttekin/PinIt-Gnome-Extension#4]
Is there maybe a way to change the icons, or to maybe hard-code the icons?

![347662383-22bbad7f-2267-414f-8250-4ba0cb2aac82](https://github.com/cankurttekin/PinIt-Gnome-Extension/assets/62904593/6323d292-0d13-4d80-abe2-c96e46e370c1)

**Comment by cankurttekin** [comment]
Which icons are missing?

This is the line for setting icons size:
https://github.com/cankurttekin/PinIt-Gnome-Extension/blob/e15e2b057542338428a9d45ae5bf644ff09b5da8/pinit%40cankurttekin/extension.js#L42C1-L42C104

**Comment by in4matix** [comment]
The two on the right

**Comment by cankurttekin** [comment]
they are not missing, with newer gnome versions they changed them to same color as any other icon but for older gnome versions warning is yellow, error is red.

**Comment by cankurttekin** [comment]
you can change icons by changing their icon names in line but if you want error and warning icon, as long as you dont apply a theme that changes pre-installed system icons, will be colored

**Comment by in4matix** [comment]
Oh I see. Won't it be better to include an icon folder in the extension folder and then rather point to those icons? That way it will also be possible to choose custom icons (just rename them to the ones you put into the icon folder and replace). Also, if a user would like to change the size of the icons (instead of messing around in the code) we can just edit the icons and resize their transparent background using an App like Gimp or BoxySVG or similar. Many other extensions use this method...

**Comment by cankurttekin** [comment]
of course, new features and improvements can certainly be done, but i will have to manage the complexity, file size, and potential issues that may arise with each addition. 
Since i dont work for gnome or 495 people who downloaded it lol. I needed this kind of simple extension when using my computer, i checked and couldnt find similiar ext or app so i made one for myself and wanted to share with people so if they like it they can use it or improve it. I like the way it works right now and i dont even use gnome 42 anymore but there were 2 issues reported by you and someone else so i fixed it for you. 

with your suggested method, when we send these icons in a file(it will be easy), we need a different approach to also send these icons to the system notifications. currently, user simply selects an icon and ext tell the system, 'You already have this icon, use it when notifying.' Coding a structure like Spotify that assigns album covers as notifications would require different implementations/functions across various GNOME versions i believe, which will be additional work for not that important customization feature. 

But this is the beauty of Free Software and Open Source, if you know how to do it than do it test it, open pr and i will update it, or you can even redistribute it.
